GET https://test.smartfleet.kz/api/resource/dependency/TaskName?lang=rus
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDgyMiwiZXhwIjoxNzY0ODUwMDI2MTE3LCJpYXQiOjE3NjQ4NDkxMjYxMTd9.rWCebqRn5cnFshZPo3Mh7x5Vabs-oJ1AgWR4csY00Tw