export enum Scopes {
  ordersMineHeader = "orders-mine-header",
  ordersMineView = "orders-mine-view",
  orderAction = "order-action",
  orderActionComplete = "order-action-complete",
  orderMain = "order-main",
  orderNext = "order-next",
  orderSave = "order-save",
  orderInitial = "order-initial",
  validateInitial = "validate-initial",
  calcRestriction = "calc-restriction",
  clientVehicles = "client-vehicles",
  newOrderParts = "new-order-parts",
  supplierList = "supplier-list",
  currentLimit = "current-limit",
  actionNewOrder = "action-new-order",
  startProcess = "start-process",
  orderHistory = "order-history",
  osmAddress = "osm-address",
  wialonAddress = "wialon-address",
}
